version: "3.9"
services:
  engine:
    build: ./engine
    container_name: chess_engine
    restart: unless-stopped
    ports:
      - "18088:18088"

  backend:
    build: ./backend
    container_name: chess_server
    depends_on:
      - engine
    environment:
      - ENGINE_HOST=${ENGINE_HOST}
      - ENGINE_PORT=${ENGINE_PORT}
    ports:
      - "49180:18080"

  frontend:
    build:
      context:
        ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_WS_URL=${VITE_WS_URL}
    container_name: chess_frontend
    depends_on:
      - backend
    ports:
      - "49181:80"
